SET(GTEST_SEARCH_PATH
    "${GTEST_SOURCE_DIR}"
    "${CMAKE_CURRENT_LIST_DIR}/../../../thirdparty/googletest/googletest")


MESSAGE(STATUS "GTEST_SOURCE_DIR: " ${GTEST_SOURCE_DIR})
MESSAGE(STATUS "GTEST_SEARCH_PATH: " ${GTEST_SEARCH_PATH})
MESSAGE(STATUS "CMAKE_CURRENT_LIST_DIR: " ${CMAKE_CURRENT_LIST_DIR})

FIND_PATH(GTEST_SOURCE_DIR
    NAMES CMakeLists.txt src/gtest_main.cc
    PATHS ${GTEST_SEARCH_PATH})

MESSAGE(STATUS "GTEST_SOURCE_DIR: " ${GTEST_SOURCE_DIR})

FIND_PATH(GTEST_INCLUDE_DIR
    NAMES gtest/gtest.h
    PATH_SUFFIXES include
    HINTS ${GTEST_SOURCE_DIR}
    PATHS ${GTEST_SEARCH_PATH})

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GOOGLETEST DEFAULT_MSG
    GTEST_SOURCE_DIR
    GTEST_INCLUDE_DIR)
