# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

#PATH=$PATH:$HOME/.local/bin:$HOME/bin

#export PATH

#export PS1="[\u@\h \w]\$ "
ulimit -c unlimited

export PATH=.:$HOME/.local/sbin/:$HOME/.local/bin:$HOME/.local/node/node-v10.13.0-linux-x64/bin:$PATH
export MANPATH=$HOME/.local/share/man:$MANPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib64:$HOME/.local/lib/
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/.local/include/:$HOME/.local/include/libxml2/
export C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/.local/include/:$HOME/.local/include/libxml2
export TMOUT=1800
