# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
#alias gcc='gcc -std=c11 -g -O0'
#alias g++='g++ -std=c++14 -g -O0'
#alias l='ls -lhF'

